apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: sample
spec:
  selector:
    app: bff
  ports:
  - name: bff
    port: 8080
    targetPort: 8080
    nodePort: 30001
  type: NodePort
