apiVersion: v1
kind: ConfigMap
metadata:
  name: next-nginx-configmap
  namespace: sample
data:
  nginx.conf: |-
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      sendfile        on;
      keepalive_timeout  65;
      server_tokens off;

      tcp_nopush          on;
      tcp_nodelay         on;
      types_hash_max_size 2048;
      client_max_body_size 20m;

      gzip              on;
      gzip_http_version 1.0;
      gzip_vary         on;
      gzip_comp_level   6;
      gzip_types        text/plain
                        text/xml
                        text/css
                        text/js
                        text/javascript
                        application/xml
                        application/javascript
                        application/json
                        application/x-javascript
                        application/font-woff
                        application/font-tff
                        application/vnd.ms-fontobject
                        application/octet-stream
                        font/ttf
                        font/opentype
                        image/svg+xml;

      server {
        listen      80 default_server;
        listen [::]:80 default_server;

        server_name _;
        root        /var/www/html;
        index       index.html;
        charset     utf-8;

        location = /health {
          access_log off;
          return 200 'ok';
        }

        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
          proxy_pass http://127.0.0.1:3000/;
        }
      }
    }
