apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: grpc
        image: grpc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
          name: grpc
        env:
          - name: GO_ENV
            value: "production"
        resources: {}
