apiVersion: v1
kind: Service
metadata:
  name: next-service
  namespace: next
spec:
  selector:
    app: next
  ports:
  - name: next
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
